import {OUTCOMES} from './constants.js';
const pct=(a,b)=> b? Math.round((a/b)*100):0;
export function filterPoints(points, f={}){ return points.filter(p=> (!f.player||f.player==='ALL'||p.player_id===f.player) && (!f.category||f.category==='ALL'||p.stroke_category===f.category) && (!f.outcome||f.outcome==='ALL'||p.outcome===f.outcome) && (!f.serve||f.serve==='ALL'||(f.serve==='SERVE' ? ['J1','J2'].includes(p.server):['R1','R2'].includes(p.server))) && (!f.highlight||f.highlight==='ALL'||String(p.highlight)===String(f.highlight))); }
export function general(points){ const total=points.length, won=points.filter(p=>p.point_result==='WON').length, lost=total-won; return {total_points:total, won_points:won, lost_points:lost, win_percentage:pct(won,total), lost_percentage:pct(lost,total), highlighted_points:points.filter(p=>+p.highlight===1).length, own_unforced_errors:points.filter(p=>p.outcome===OUTCOMES.OWN_UNFORCED_ERROR).length, winner_or_forced:points.filter(p=>p.outcome===OUTCOMES.WINNER_OR_FORCED).length}; }
export function byPlayer(points, player){ const pp=points.filter(p=>p.player_id===player); const pos=pp.filter(p=>p.outcome===OUTCOMES.WINNER_OR_FORCED).length; const neg=pp.filter(p=>[OUTCOMES.OWN_UNFORCED_ERROR,OUTCOMES.RIVAL_WINNER_OR_OWN_FORCED].includes(p.outcome)).length; return {player, won_by_player:pp.filter(p=>p.point_result==='WON').length, lost_by_player:pp.filter(p=>p.point_result==='LOST').length, own_unforced_errors:pp.filter(p=>p.outcome===OUTCOMES.OWN_UNFORCED_ERROR).length, winner_or_forced:pos, rival_winner_or_own_forced:pp.filter(p=>p.outcome===OUTCOMES.RIVAL_WINNER_OR_OWN_FORCED).length, balance:pos-neg}; }
export function service(points){ const serve=points.filter(p=>['J1','J2'].includes(p.server)), ret=points.filter(p=>['R1','R2'].includes(p.server)); const first=points.filter(p=>p.serve_number==='1º'), second=points.filter(p=>p.serve_number==='2º'); return {serve_points:serve.length, return_points:ret.length, serve_pct:pct(serve.length,points.length), return_pct:pct(ret.length,points.length), first_serve_points:first.length, second_serve_points:second.length, first_serve_won:first.filter(p=>p.point_result==='WON').length, second_serve_won:second.filter(p=>p.point_result==='WON').length, first_serve_win_pct:pct(first.filter(p=>p.point_result==='WON').length,first.length), second_serve_win_pct:pct(second.filter(p=>p.point_result==='WON').length,second.length), return_vs_first_serve_won_pct:pct(ret.filter(p=>p.serve_number==='1º'&&p.point_result==='WON').length,ret.filter(p=>p.serve_number==='1º').length), return_vs_second_serve_won_pct:pct(ret.filter(p=>p.serve_number==='2º'&&p.point_result==='WON').length,ret.filter(p=>p.serve_number==='2º').length)}; }
function group(points,key){ return points.reduce((a,p)=>{ const k=p[key]||'Sin dato'; a[k]=(a[k]||0)+1; return a;},{}); }
export function categories(points){ return {positive:group(points.filter(p=>p.outcome===OUTCOMES.WINNER_OR_FORCED),'stroke_category'), unforced:group(points.filter(p=>p.outcome===OUTCOMES.OWN_UNFORCED_ERROR),'stroke_category'), forcedLost:group(points.filter(p=>p.outcome===OUTCOMES.RIVAL_WINNER_OR_OWN_FORCED),'stroke_category')}; }
export function topStrokes(points){ const map={}; points.forEach(p=>{ if(!p.stroke_type) return; const k=`${p.stroke_category} · ${p.stroke_type}`; map[k]??={stroke:k,total:0,pos:0,neg:0,balance:0}; map[k].total++; if(p.outcome===OUTCOMES.WINNER_OR_FORCED) map[k].pos++; if([OUTCOMES.OWN_UNFORCED_ERROR,OUTCOMES.RIVAL_WINNER_OR_OWN_FORCED].includes(p.outcome)) map[k].neg++; map[k].balance=map[k].pos-map[k].neg; }); const arr=Object.values(map).sort((a,b)=>b.total-a.total); return {frequent:arr.slice(0,5), positive:[...arr].sort((a,b)=>b.balance-a.balance).slice(0,5), negative:[...arr].sort((a,b)=>a.balance-b.balance).slice(0,5)}; }
export function zones(points){ return group(points.filter(p=>p.outcome===OUTCOMES.RIVAL_UNFORCED_ERROR),'court_zone'); }
export function rally(points){ const g=group(points,'rally'); return Object.entries(g).map(([range,total])=>({range,total,won:points.filter(p=>p.rally===range&&p.point_result==='WON').length,winPct:pct(points.filter(p=>p.rally===range&&p.point_result==='WON').length,total)})); }
