import {general, service, byPlayer, topStrokes} from './analytics.js';
import {loadDB, matchSets} from './storage.js';
function setPoints(db,setId){ return db.points.filter(p=>p.set_id===setId); }
function playerRows(points, match){ const j1=byPlayer(points,'J1'), j2=byPlayer(points,'J2'); return [[match?.player_j1_name||'Revés/J1',j1.won_by_player,j1.lost_by_player,j1.own_unforced_errors,j1.winner_or_forced,j1.rival_winner_or_own_forced,j1.balance],[match?.player_j2_name||'Derecha/J2',j2.won_by_player,j2.lost_by_player,j2.own_unforced_errors,j2.winner_or_forced,j2.rival_winner_or_own_forced,j2.balance]]; }
function serviceRows(points){ const s=service(points); return [['1º saque',s.first_serve_points,s.first_serve_won,s.first_serve_points-s.first_serve_won,`${s.first_serve_win_pct}%`],['2º saque',s.second_serve_points,s.second_serve_won,s.second_serve_points-s.second_serve_won,`${s.second_serve_win_pct}%`],['Resto vs 1º',points.filter(p=>['R1','R2'].includes(p.server)&&p.serve_number==='1º').length,points.filter(p=>['R1','R2'].includes(p.server)&&p.serve_number==='1º'&&p.point_result==='WON').length,points.filter(p=>['R1','R2'].includes(p.server)&&p.serve_number==='1º'&&p.point_result==='LOST').length,`${s.return_vs_first_serve_won_pct}%`],['Resto vs 2º',points.filter(p=>['R1','R2'].includes(p.server)&&p.serve_number==='2º').length,points.filter(p=>['R1','R2'].includes(p.server)&&p.serve_number==='2º'&&p.point_result==='WON').length,points.filter(p=>['R1','R2'].includes(p.server)&&p.serve_number==='2º'&&p.point_result==='LOST').length,`${s.return_vs_second_serve_won_pct}%`]]; }
function donutDataUrl(parts){
  const c=document.createElement('canvas'); c.width=240; c.height=240; const ctx=c.getContext('2d'); const cx=120, cy=120, r=88; let start=-Math.PI/2; const total=parts.reduce((a,p)=>a+p.value,0)||1;
  ctx.fillStyle='#ffffff'; ctx.fillRect(0,0,240,240);
  for(const p of parts){ const angle=(p.value/total)*Math.PI*2; ctx.beginPath(); ctx.moveTo(cx,cy); ctx.arc(cx,cy,r,start,start+angle); ctx.closePath(); ctx.fillStyle=p.color; ctx.fill(); start+=angle; }
  ctx.beginPath(); ctx.arc(cx,cy,48,0,Math.PI*2); ctx.fillStyle='#ffffff'; ctx.fill();
  ctx.fillStyle='#203d32'; ctx.font='bold 28px Arial'; ctx.textAlign='center'; ctx.textBaseline='middle'; ctx.fillText(`${Math.round((parts[0]?.value||0)/total*100)}%`,cx,cy);
  return c.toDataURL('image/png');
}
function addDonuts(doc, x, y, charts){
  charts.forEach((ch,i)=>{ const dx=x+i*170; doc.addImage(donutDataUrl(ch.parts),'PNG',dx,y,88,88); doc.setFont('helvetica','bold'); doc.setFontSize(9); doc.text(ch.label,dx+44,y+105,{align:'center'}); doc.setFont('helvetica','normal'); doc.text(ch.sub,dx+44,y+119,{align:'center'}); });
}
function kpiCards(doc, y, rows){
  rows.forEach((r,i)=>{ const x=40+i*126; doc.setFillColor(247,243,235); doc.roundedRect(x,y,112,52,10,10,'F'); doc.setFontSize(8); doc.setTextColor(90,98,92); doc.text(r[0],x+10,y+18); doc.setFont('helvetica','bold'); doc.setFontSize(17); doc.setTextColor(32,61,50); doc.text(String(r[1]),x+10,y+40); doc.setFont('helvetica','normal'); }); doc.setTextColor(0,0,0);
}
export async function downloadPDF(points, match, name='santiset-informe.pdf'){
  const {jsPDF}=window.jspdf; const doc=new jsPDF({unit:'pt',format:'a4'}); const db=loadDB(); const sets=matchSets(db,match?.id); const g=general(points);
  doc.setFillColor(31,77,61); doc.rect(0,0,595,96,'F'); doc.setTextColor(255,255,255); doc.setFont('helvetica','bold'); doc.setFontSize(24); doc.text('SantiSet · Informe de partido',40,48); doc.setFontSize(11); doc.setFont('helvetica','normal'); doc.text(`${match?.rival_name||'Partido'} · ${new Date(match?.date||match?.created_at||Date.now()).toLocaleString('es-ES')}`,40,70); doc.setTextColor(0,0,0);
  const info=[['Pareja rival',match?.rival_name||'-'],['Compañero',match?.partner_name||'-'],['Fecha',new Date(match?.date||match?.created_at||Date.now()).toLocaleString('es-ES')],['Tipo',match?.match_type||'-'],['Lugar',match?.location||'-'],['Tipo pista',match?.court_type||'-'],['Notas',match?.notes||'-']];
  doc.autoTable({startY:120, head:[['Dato','Valor']], body:info, styles:{fontSize:9}, headStyles:{fillColor:[31,77,61]}});
  const y=doc.lastAutoTable.finalY+24; kpiCards(doc,y,[['Puntos',g.total_points],['Ganados',g.won_points],['Perdidos',g.lost_points],['Destacados',g.highlighted_points]]);
  addDonuts(doc,55,y+78,[{label:'Ganados / perdidos',sub:`${g.won_points}G · ${g.lost_points}P`,parts:[{value:g.won_points,color:'#1f7a42'},{value:g.lost_points,color:'#b42323'}]},{label:'Destacados',sub:`${g.highlighted_points}/${g.total_points}`,parts:[{value:g.highlighted_points,color:'#d66b1f'},{value:Math.max(0,g.total_points-g.highlighted_points),color:'#e4e8e3'}]}]);
  for(const set of sets){ const pts=setPoints(db,set.id); const sg=general(pts); const srv=service(pts); doc.addPage(); doc.setTextColor(31,77,61); doc.setFont('helvetica','bold'); doc.setFontSize(19); doc.text(`Set ${set.set_number||1} · ${set.our_games}-${set.rival_games}`,40,54); doc.setTextColor(0,0,0); kpiCards(doc,76,[['Puntos',sg.total_points],['Ganados',sg.won_points],['Perdidos',sg.lost_points],['% ganado',`${sg.win_percentage}%`]]); addDonuts(doc,55,150,[{label:'Ganados / perdidos',sub:`${sg.won_points}G · ${sg.lost_points}P`,parts:[{value:sg.won_points,color:'#1f7a42'},{value:sg.lost_points,color:'#b42323'}]},{label:'1º saque',sub:`${srv.first_serve_won}/${srv.first_serve_points}`,parts:[{value:srv.first_serve_won,color:'#285c96'},{value:Math.max(0,srv.first_serve_points-srv.first_serve_won),color:'#e4e8e3'}]},{label:'2º saque',sub:`${srv.second_serve_won}/${srv.second_serve_points}`,parts:[{value:srv.second_serve_won,color:'#285c96'},{value:Math.max(0,srv.second_serve_points-srv.second_serve_won),color:'#e4e8e3'}]}]); doc.setFont('helvetica','bold'); doc.setFontSize(13); doc.text('Análisis por jugador',40,300); doc.autoTable({startY:312, head:[['Jugador','Ganados','Perdidos','ENF','W/F','Forzados perdidos','Balance']], body:playerRows(pts,match), headStyles:{fillColor:[31,77,61]}}); doc.text('Servicio y resto',40,doc.lastAutoTable.finalY+30); doc.autoTable({startY:doc.lastAutoTable.finalY+42, head:[['Bloque','Jugados','Ganados','Perdidos','%']], body:serviceRows(pts), headStyles:{fillColor:[40,92,150]}}); const tops=topStrokes(pts); doc.text('Golpes destacados',40,doc.lastAutoTable.finalY+30); doc.autoTable({startY:doc.lastAutoTable.finalY+42, head:[['Golpe','Total','Positivos','Negativos','Balance']], body:(tops.positive.concat(tops.negative)).slice(0,10).map(x=>[x.stroke,x.total,x.pos,x.neg,x.balance]), headStyles:{fillColor:[210,95,28]}}); }
  doc.save(name);
}
